#!/usr/bin/env node

var ReactApp  = require('./index'),
    version   = require('./package.json').version,
    fs        = require('fs'),
    p         = require('path'),
    wrap      = require('wordwrap')(79),
    optimist  = require('optimist')
      .usage('$0 [options]')
      .option('h', {
        alias: 'help',
        boolean: true,
        describe: 'Show this message and exit'
      })
      .option('v', {
        alias: 'version',
        boolean: true,
        describe: 'Show version'
      })
      .option('d', {
        alias: 'debug',
        boolean: true,
        describe: 'Run in debug mode'
      })
      .option('p', {
        alias: 'port',
        describe: 'Port to use (default: 3000)'
      })
      .option('host', {
        describe: 'Host to use (default: localhost)'
      })
      .option('t', {
        alias: 'transform',
        describe: 'Apply dcompose transform'
      })
      .option('routes', {
        describe: 'Use routes definition'
      })

if (optimist.argv.help) return optimist.showHelp();
if (optimist.argv.version) return console.log(version);

var argv = optimist.argv;

switch (argv._[0]) {
  case 'serve':
    var id = argv._[1];
    if (!id) error('provide module id as an argument');
    ReactApp(id, argv).listen(argv.port || 3000, argv.host || 'localhost');
    break;
  case 'bundle':
    error('not implemented');
    break;
  default:
    error('unknown command ' + argv._[0]);
}

function error(msg) {
  console.error(wrap('error: ' + msg));
  process.exit(1);
}
